### ISSUE TITLE
pip install issue

### ISSUE THREAD

**Issue by qihongl** [kristianeschenburg/ddCRP#2]
Hi, I tried pip installing this package and got the following error message: 
```
Qihong@:ddCRP$ pip install . 
Processing /Users/Qihong/Dropbox/github/ddCRP
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/qf/61j5g_4s3cbch094b5_dcdp40000gn/T/pip-req-build-mgly4i7y/setup.py", line 26, in <module>
        with open(path.join(here, 'README.rst'), encoding='utf-8') as readme_file:
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/qf/61j5g_4s3cbch094b5_dcdp40000gn/T/pip-req-build-mgly4i7y/README.rst'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/qf/61j5g_4s3cbch094b5_dcdp40000gn/T/pip-req-build-mgly4i7y/
```

Any clue about what's happening? I'm using python 3.7. 

Thanks!

**Comment by kristianeschenburg** [comment]
pip install . requires a restructured text-formatted README.rst file -- I've converted the README.md to README.rst using the Python package **m2r** (https://pypi.org/project/m2r/).  The install should work now.
